/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as FidelizacaoRouteImport } from './routes/fidelizacao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicInfinitepayWebhookRouteImport } from './routes/api/public/infinitepay-webhook'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const FidelizacaoRoute = FidelizacaoRouteImport.update({
  id: '/fidelizacao',
  path: '/fidelizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInfinitepayWebhookRoute =
  ApiPublicInfinitepayWebhookRouteImport.update({
    id: '/api/public/infinitepay-webhook',
    path: '/api/public/infinitepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fidelizacao': typeof FidelizacaoRoute
  '/servicos': typeof ServicosRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fidelizacao': typeof FidelizacaoRoute
  '/servicos': typeof ServicosRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fidelizacao': typeof FidelizacaoRoute
  '/servicos': typeof ServicosRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/fidelizacao'
    | '/servicos'
    | '/api/public/infinitepay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/fidelizacao'
    | '/servicos'
    | '/api/public/infinitepay-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/fidelizacao'
    | '/servicos'
    | '/api/public/infinitepay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CaixaRoute: typeof CaixaRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FidelizacaoRoute: typeof FidelizacaoRoute
  ServicosRoute: typeof ServicosRoute
  ApiPublicInfinitepayWebhookRoute: typeof ApiPublicInfinitepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelizacao': {
      id: '/fidelizacao'
      path: '/fidelizacao'
      fullPath: '/fidelizacao'
      preLoaderRoute: typeof FidelizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/infinitepay-webhook': {
      id: '/api/public/infinitepay-webhook'
      path: '/api/public/infinitepay-webhook'
      fullPath: '/api/public/infinitepay-webhook'
      preLoaderRoute: typeof ApiPublicInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CaixaRoute: CaixaRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FidelizacaoRoute: FidelizacaoRoute,
  ServicosRoute: ServicosRoute,
  ApiPublicInfinitepayWebhookRoute: ApiPublicInfinitepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
